{
    "debug": false,
    "featureManagerIsAlwaysOnlineEnabled": true,
    "featureManagerIsBrowserCacheTTLEnabled": true,
    "featureManagerIsBrowserIntegrityCheckEnabled": true,
    "featureManagerIsCacheLevelEnabled": true,
    "featureManagerIsChallengePassageEnabled": true,
    "featureManagerIsDevelopmentModeEnabled": true,
    "featureManagerIsFullZoneProvisioningEnabled": false,
    "featureManagerIsImageOptimizationEnabled": true,
    "featureManagerIsIpv6Enabled": true,
    "featureManagerIsIpRewriteEnabled": true,
    "featureManagerIsMinifyEnabled": true,
    "featureManagerIsProtocolRewriteEnabled": true,
    "featureManagerIsPurgeCacheEnabled": true,
    "featureManagerIsRailgunEnabled": true,
    "featureManagerIsScanEnabled": false,
    "featureManagerIsSecurityLevelEnabled": true,
    "featureManagerIsSSLEnabled": false,
    "featureManagerIsWAFEnabled": true,
    "homePageCards": ["ApplyDefaultSettingsCard", "PluginSpecificCacheTagCard", "PurgeCacheCard"],
    "moreSettingsCards": {
        "container.moresettings.security": ["SecurityLevelCard"],
        "container.moresettings.speed": ["AlwaysOnlineCard", "ImageOptimizationCard"]
    },
    "locale": "en",
    "integrationName": "Magento",
    "useHostAPILogin": false,
    "version": "1.0.8"
}