<script>
    /*
     * A callback for cf-util-http to proxy all calls to our backend
     *
     * @param {Object} [opts]
     * @param {String} [opts.method] - GET/POST/PUT/PATCH/DELETE
     * @param {String} [opts.url]
     * @param {Object} [opts.parameters]
     * @param {Object} [opts.headers]
     * @param {Object} [opts.body]
     * @param {Function} [opts.onSuccess]
     * @param {Function} [opts.onError]
     */
    var absoluteUrlBase = '<?php echo $this->getRestProxyPrefix(); ?>';
    function RestProxyCallback(opts) {
        //only proxy external REST calls
        if(opts.url.lastIndexOf("http", 0) === 0) {
            if(opts.method.toUpperCase() !== "GET") {
                if(!opts.body) {
                    opts.body = {};
                }
                opts.body['cfCSRFToken'] = cfCSRFToken;
                opts.body['proxyURL'] = opts.url;
            } else {
                if(!opts.parameters) {
                    opts.parameters = {};
                }
                opts.parameters['proxyURL'] = opts.url;
            }
            opts.url = "./proxy.live.php";
        } else {
            opts.url = absoluteUrlBase + opts.url;
        }
    }
</script>
<div id="root" class="cloudflare-partners site-wrapper"></div>
<script src="<?php echo $this->getCompiledJsUrl(); ?>"></script>